// Auto-generated by scripts/evolve.js - best genome found by offline
// evolution, re-scored on the full answer list. Do not edit by hand.
export const CHAMPION = {
  "genome": {
    "wPos": 0.1806744096102193,
    "wFreq": 0.8891339213623723,
    "wInfo": 0.7410333967272891,
    "wUnique": 0,
    "wCand": 0.5684275536473251,
    "commitCount": 40,
    "commitTurn": 4
  },
  "opener": "alter",
  "avgGuesses": 3.6469,
  "solveRate": 0.9922,
  "generation": 17,
  "traits": "mild split-seeker, probes long, impatient closer"
};
