// Auto-generated by scripts/evolve.js - best genome found by offline
// evolution, re-scored on the full answer list. Do not edit by hand.
export const CHAMPION = {
  "genome": {
    "wPos": 1.4942122015927453,
    "wFreq": 1.5568764041381655,
    "wInfo": 0.8027536870176846,
    "wUnique": 0.003318210714496672,
    "wCand": 1.045293678082817,
    "wCommon": 0.39259445845891605,
    "commitCount": 43,
    "commitTurn": 2
  },
  "opener": "alert",
  "avgGuesses": 3.6401,
  "solveRate": 0.9927,
  "generation": 18,
  "traits": "mild split-seeker, position-driven, frequency-driven, go-for-the-win, commits early, impatient closer"
};
