// Builds core/freqs.js: how common each legal guess word is in English,
// derived from Peter Norvig's unigram counts (Google Web Trillion Word
// Corpus, https://norvig.com/ngrams/count_1w.txt).
// Run: node scripts/build-freqs.js [path/to/count_1w.txt]
// Without a path argument the list is fetched from norvig.com.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { ALL_WORDS } from '../core/words.js';

const src = process.argv[2];
const text = src
  ? readFileSync(src, 'utf8')
  : await (await fetch('https://norvig.com/ngrams/count_1w.txt')).text();

const counts = new Map();
for (const line of text.split('\n')) {
  const [word, count] = line.split('\t');
  if (word && word.length === 5 && /^[a-z]{5}$/.test(word)) {
    counts.set(word, Number(count));
  }
}

// Normalize log-counts of the words we actually use to 0..99.
const logs = ALL_WORDS.map((w) => (counts.has(w) ? Math.log(counts.get(w)) : null));
const seen = logs.filter((v) => v !== null);
const lo = Math.min(...seen), hi = Math.max(...seen);
const digits = logs
  .map((v) => (v === null ? 0 : Math.round(((v - lo) / (hi - lo)) * 99)))
  .map((d) => String(d).padStart(2, '0'))
  .join('');

const matched = seen.length;
const out =
  `// Auto-generated by scripts/build-freqs.js - English commonness of every\n` +
  `// legal guess word (Norvig's web-corpus unigram counts, log-scaled to\n` +
  `// 0..99, two digits per word in ALL_WORDS order). Do not edit by hand.\n` +
  `import { ALL_WORDS } from './words.js';\n` +
  `\n` +
  `const DIGITS = '${digits}';\n` +
  `\n` +
  `const table = new Map();\n` +
  `for (let i = 0; i < ALL_WORDS.length; i++) {\n` +
  `  table.set(ALL_WORDS[i], Number(DIGITS.slice(i * 2, i * 2 + 2)) / 99);\n` +
  `}\n` +
  `\n` +
  `/** How common a word is in English: 0 (unseen or rare) to 1 (most common). */\n` +
  `export function commonness(word) {\n` +
  `  return table.get(word) || 0;\n` +
  `}\n`;

const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(join(here, '../core/freqs.js'), out);
console.log(`Matched ${matched}/${ALL_WORDS.length} words; wrote core/freqs.js`);
for (const w of ['about', 'brain', 'mouse', 'soare', 'betel', 'xylyl']) {
  const v = counts.has(w) ? Math.round(((Math.log(counts.get(w)) - lo) / (hi - lo)) * 99) : 0;
  console.log(`  ${w}: ${v}`);
}
