// Evolves the genetic-algorithm population offline and writes the best genome
// found to core/champion.js (used as the default GA opponent by the site and
// the Discord bot). Run: npm run evolve [-- generations population games]
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { GeneticEvolver, describeGenome, evaluateGenome } from '../core/genetic.js';
import { ANSWERS } from '../core/words.js';

const [gens = 40, pop = 120, games = 40] = process.argv.slice(2).map(Number);

const evolver = new GeneticEvolver({
  populationSize: pop,
  gamesPerAgent: games,
  seed: 20260704,
});

console.log(`Evolving ${pop} agents for ${gens} generations (${games} games each)...`);
const t0 = Date.now();
for (let g = 0; g < gens; g++) {
  const r = evolver.step();
  const line = `gen ${String(r.generation).padStart(3)}  best avg ${r.best.avgGuesses.toFixed(3)} ` +
    `(${(r.best.solveRate * 100).toFixed(0)}% solved, opener "${r.best.opener}")  ` +
    `pop mean ${r.meanAvgGuesses.toFixed(3)}`;
  console.log(line);
}
console.log(`Evolution took ${((Date.now() - t0) / 1000).toFixed(1)}s`);

// Re-score the champion on the FULL answer list for honest final numbers.
const champ = evolver.champion;
console.log('\nScoring champion on all answers...');
const full = evaluateGenome(champ.genome, ANSWERS);
console.log(`Champion: avg ${full.avgGuesses.toFixed(3)} guesses, ` +
  `${(full.solveRate * 100).toFixed(1)}% solve rate, opener "${full.opener}"`);
console.log(`Traits: ${describeGenome(champ.genome)}`);

const out =
  `// Auto-generated by scripts/evolve.js - best genome found by offline\n` +
  `// evolution, re-scored on the full answer list. Do not edit by hand.\n` +
  `export const CHAMPION = ${JSON.stringify({
    genome: champ.genome,
    opener: full.opener,
    avgGuesses: +full.avgGuesses.toFixed(4),
    solveRate: +full.solveRate.toFixed(4),
    generation: champ.generation,
    traits: describeGenome(champ.genome),
  }, null, 2)};\n`;

const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(join(here, '../core/champion.js'), out);
console.log('Wrote core/champion.js');
