// Computes the entropy of every legal first guess against the full answer set
// and writes the top 150 to core/openers.js. Run once: npm run precompute
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { ALL_WORDS, ANSWERS } from '../core/words.js';
import { rankGuesses } from '../core/entropy.js';
import { allCandidateIndices } from '../core/tables.js';

const t0 = Date.now();
const ranked = rankGuesses(allCandidateIndices(), { topN: 150, guessPool: ALL_WORDS });
const secs = ((Date.now() - t0) / 1000).toFixed(1);

const rounded = ranked.map((r) => ({
  word: r.word,
  entropy: +r.entropy.toFixed(4),
  isCandidate: r.isCandidate,
  winChance: +r.winChance.toFixed(6),
  expectedRemaining: +r.expectedRemaining.toFixed(2),
  score: +r.score.toFixed(4),
}));

const out =
  `// Auto-generated by scripts/precompute-openers.js - entropy of the best\n` +
  `// first guesses against all ${ANSWERS.length} answers. Do not edit by hand.\n` +
  `export const OPENERS = ${JSON.stringify(rounded)};\n`;

const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(join(here, '../core/openers.js'), out);
console.log(`Computed ${ALL_WORDS.length} first-guess entropies in ${secs}s`);
console.log('Top 5 openers:');
for (const r of rounded.slice(0, 5)) {
  console.log(`  ${r.word}  ${r.entropy.toFixed(3)} bits  (expected remaining: ${r.expectedRemaining})`);
}
